
import { Leaf, SewingNeedle, Plant } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";

const AboutPage = () => {
  return (
    <div>
      {/* Hero Section */}
      <section className="bg-gray-50 py-16">
        <div className="container-padding">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-5xl font-bold text-rewear-green mb-6">Our Story</h1>
            <p className="text-xl text-gray-600">
              ReWear was born from a simple idea: fashion shouldn't come at the cost of our planet.
            </p>
          </div>
        </div>
      </section>

      {/* Our Journey */}
      <section className="py-16">
        <div className="container-padding">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="section-title">How It All Started</h2>
              <p className="text-gray-600 mb-6">
                In 2018, our founder Emma observed the massive amount of textile waste generated by the fashion industry. Driven by a passion for sustainability and design, she began collecting discarded clothing and transforming them into new, stylish pieces.
              </p>
              <p className="text-gray-600 mb-6">
                What started as a small project in a tiny apartment soon grew into a movement. Local artisans joined in, bringing their skills and creativity, and ReWear was born - a brand dedicated to proving that fashion can be both beautiful and sustainable.
              </p>
              <p className="text-gray-600">
                Today, we work with over 140 artisans worldwide, have saved thousands of garments from landfills, and continue to push the boundaries of sustainable fashion.
              </p>
            </div>
            <div className="order-first lg:order-last">
              <img
                src="https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&auto=format"
                alt="ReWear founder working on designs"
                className="rounded-lg shadow-md"
              />
            </div>
          </div>
        </div>
      </section>

      {/* Our Values */}
      <section className="py-16 bg-gray-50">
        <div className="container-padding">
          <h2 className="section-title text-center mb-12">Our Values</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-white p-8 rounded-lg shadow-sm text-center">
              <div className="bg-rewear-green/10 p-4 inline-block rounded-full mb-4">
                <Leaf className="h-8 w-8 text-rewear-green" />
              </div>
              <h3 className="text-xl font-medium mb-3">Sustainability</h3>
              <p className="text-gray-600">
                We're committed to reducing fashion's environmental impact through upcycling, 
                minimal waste production, and eco-friendly practices.
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm text-center">
              <div className="bg-rewear-green/10 p-4 inline-block rounded-full mb-4">
                <SewingNeedle className="h-8 w-8 text-rewear-green" />
              </div>
              <h3 className="text-xl font-medium mb-3">Craftsmanship</h3>
              <p className="text-gray-600">
                We celebrate and preserve traditional craft techniques, working with skilled 
                artisans and providing fair compensation for their expertise.
              </p>
            </div>
            
            <div className="bg-white p-8 rounded-lg shadow-sm text-center">
              <div className="bg-rewear-green/10 p-4 inline-block rounded-full mb-4">
                <Plant className="h-8 w-8 text-rewear-green" />
              </div>
              <h3 className="text-xl font-medium mb-3">Community</h3>
              <p className="text-gray-600">
                We believe in the power of community to drive change, supporting local initiatives 
                and educational programs in the regions where we work.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Our Process */}
      <section className="py-16">
        <div className="container-padding">
          <div className="text-center mb-12">
            <h2 className="section-title">How We Work</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Our process transforms discarded clothing into unique, high-quality pieces while 
              supporting communities and reducing waste.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="text-center">
              <div className="bg-rewear-blue/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-rewear-blue">1</span>
              </div>
              <h3 className="font-medium mb-2">Collection</h3>
              <p className="text-gray-600 text-sm">
                We collect pre-loved clothing through donations and community drives.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-rewear-blue/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-rewear-blue">2</span>
              </div>
              <h3 className="font-medium mb-2">Sorting & Design</h3>
              <p className="text-gray-600 text-sm">
                Our team sorts materials and creates new designs based on available fabrics.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-rewear-blue/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-rewear-blue">3</span>
              </div>
              <h3 className="font-medium mb-2">Artisan Creation</h3>
              <p className="text-gray-600 text-sm">
                Skilled artisans transform materials into beautiful new garments and accessories.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-rewear-blue/10 h-16 w-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl font-bold text-rewear-blue">4</span>
              </div>
              <h3 className="font-medium mb-2">Impact</h3>
              <p className="text-gray-600 text-sm">
                Products are sold, with proceeds supporting artisans and community programs.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Team Section */}
      <section className="py-16 bg-gray-50">
        <div className="container-padding">
          <div className="text-center mb-12">
            <h2 className="section-title">Meet Our Team</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              The passionate people behind ReWear who make our vision a reality.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* Team member 1 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-sm">
              <img
                src="https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&auto=format"
                alt="Emma Chen - Founder"
                className="w-full h-64 object-cover object-center"
              />
              <div className="p-6">
                <h3 className="text-lg font-medium mb-1">Emma Chen</h3>
                <p className="text-rewear-green mb-3">Founder & Creative Director</p>
                <p className="text-gray-600 text-sm">
                  A fashion designer with a background in environmental science, Emma combines her 
                  passions to drive ReWear's mission forward.
                </p>
              </div>
            </div>

            {/* Team member 2 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-sm">
              <img
                src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format"
                alt="James Roberts - Operations Director"
                className="w-full h-64 object-cover object-center"
              />
              <div className="p-6">
                <h3 className="text-lg font-medium mb-1">James Roberts</h3>
                <p className="text-rewear-green mb-3">Operations Director</p>
                <p className="text-gray-600 text-sm">
                  With 15 years in ethical supply chains, James ensures our processes remain sustainable 
                  and impactful at every stage.
                </p>
              </div>
            </div>

            {/* Team member 3 */}
            <div className="bg-white rounded-lg overflow-hidden shadow-sm">
              <img
                src="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format"
                alt="Priya Sharma - Community Manager"
                className="w-full h-64 object-cover object-center"
              />
              <div className="p-6">
                <h3 className="text-lg font-medium mb-1">Priya Sharma</h3>
                <p className="text-rewear-green mb-3">Community Manager</p>
                <p className="text-gray-600 text-sm">
                  Priya oversees our artisan partnerships and community outreach programs, ensuring 
                  positive impact in all the communities we work with.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-rewear-blue text-white">
        <div className="container-padding text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-6">Join Our Journey</h2>
          <p className="text-white/80 max-w-2xl mx-auto mb-8">
            Be part of our mission to revolutionize fashion. Shop our collections, donate your clothes, 
            or simply spread the word about sustainable fashion.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild className="bg-white text-rewear-blue hover:bg-gray-100">
              <Link to="/shop">Browse Collections</Link>
            </Button>
            <Button asChild variant="outline" className="border-white text-white hover:bg-white/10">
              <Link to="/contact">Get In Touch</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default AboutPage;
